version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: easycrud-backend
    ports:
      - "8080:8080"
    networks:
      - easycrud-network

  frontend:
    build:
      context: ./frontend
      args:
        BACKEND_HOST: backend
        BACKEND_PORT: 8080
    container_name: easycrud-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - easycrud-network

networks:
  easycrud-network:
    driver: bridge
